version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /home/circleci/hugo
    environment:
      HUGO_DIR: /home/circleci/hugo
      HUGO_BUILD_DIR: /home/circleci/hugo/public
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: sudo apt update && sudo apt install git
      - run:
          name: Fetch theme repository submodule
          command: git submodule add -f https://github.com/tgrk/hugo-nuo $HUGO_DIR/themes/hugo-nuo

      - run:
          name: Install lftp
          command: |
            sudo apt install lftp

      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: Test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

      - deploy:
          name: Deploy to Wedos
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              lftp -e "mirror -R $HUGO_BUILD_DIR/ /www/domains/wiso.cz/; quit" -u $FTP_USER,$FTP_PASSWD $FTP_HOST
            else
              echo "Not master branch, dry run only"
            fi
