version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /root/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'e0:74:8e:9c:48:05:54:25:eb:4d:b2:2f:0e:5f:1b:3f'

      - run: apk update && apk add git
      - run: cd themes && git clone git@github.com:laozhu/hugo-nuo.git && cd ..

      - run:
          name: Install lftp
          command: |
            apk add --update lftp

      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: Copy theme fonts
          command: cp -R /root/hugo/themes/hugo-nuo/static/fonts /root/hugo/public

      - run:
          name: Test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

      - deploy:
          name: Deploy to Wedos
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              lftp -e "mirror -R $HUGO_BUILD_DIR/ /www/domains/wiso.cz/; quit" -u $FTP_USER,$FTP_PASSWD $FTP_HOST
            else
              echo "Not master branch, dry run only"
            fi
