version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /root/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public
    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run:
          name: Install dependencies
          command: apk update && apk add git
      - run:
          name: Clone theme repository
          command: git clone https://github.com/laozhu/hugo-nuo.git themes/hugo-nuo

      - run:
          name: Install lftp
          command: |
            apk add --update lftp

      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: Copy theme fonts
          command: cp -R /root/hugo/themes/hugo-nuo/static/fonts /root/hugo/public

      - run:
          name: Test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

      - deploy:
          name: Deploy to Wedos
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              lftp -e "mirror -R $HUGO_BUILD_DIR/ /www/domains/wiso.cz/; quit" -u $FTP_USER,$FTP_PASSWD $FTP_HOST
            else
              echo "Not master branch, dry run only"
            fi
